site_name: "aria2p"
site_description: "Command-line tool and Python library to interact with an aria2c daemon process through JSON-RPC."
site_url: "https://pawamoy.github.io/aria2p"
repo_url: "https://github.com/pawamoy/aria2p"
repo_name: "pawamoy/aria2p"

nav:
- Overview: index.md
- Usage: usage.md
- Configuration: configuration.md
- API Reference:
  - api.py: reference/api.md
  - cli.py: reference/cli.md
  - client.py: reference/client.md
  - downloads.py: reference/downloads.md
  - options.py: reference/options.md
  - stats.py: reference/stats.md
  - utils.py: reference/utils.md
- Contributing: contributing.md
- Code of Conduct: code_of_conduct.md
- Changelog: changelog.md
- Coverage: coverage.md
- Credits: credits.md

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
- css/custom.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- coverage:
    html_report_dir: build/coverage
- mkdocstrings:
    watch:
    - src/aria2p

